### Requisição GET de categorias de produtos
GET http://localhost:3000/categories HTTP/1.1
Content-Type: application/json

### Requisição GET de uma categoria específica
GET http://localhost:3000/categories/1 HTTP/1.1
Content-Type: application/json

### Requisição GET de produtos por categoria
GET http://localhost:3000/burgers?categoryId=1 HTTP/1.1
Content-Type: application/json

### Requisição GET de produto de uma categoria
GET http://localhost:3000/burgers?id=9 HTTP/1.1
Content-Type: application/json

### Requisição GET de pediddos
GET http://localhost:3000/orders HTTP/1.1
Content-Type: application/json

### Requisição GET de um pedido específico
GET http://localhost:3000/orders/112 HTTP/1.1
Content-Type: application/json

### Requisição POST
POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json

{
  "id": "112",
  "burger1": {
    "name": "X-Proteína",
    "quantity": 2
  },
  "burger2": {
    "name": "X-Alface-Premium",
    "quantity": 3
  },
  "observation": "Sem molho"
}
